"""The Astral tool catalog, loaded from the checked-in server contract.

``work_contract.json`` is generated by ``scripts/export_work_contract.py``
from Deep's own ``orchestrator.mcp_projection``/``orchestrator.work_operations``
source — this module never hand-types a tool name, scope or schema. A
repository-level test (``scripts/tests/test_export_work_contract.py``) pins
that the checked-in file matches a fresh export from the current backend.
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Any

_CONTRACT_PATH = Path(__file__).resolve().parent / "work_contract.json"


def _load_contract() -> dict[str, Any]:
    with _CONTRACT_PATH.open("r", encoding="utf-8") as handle:
        return json.load(handle)


#: The full exported contract (mcp metadata, scopes, tool specs, operation shape).
CONTRACT: dict[str, Any] = _load_contract()

#: ``{tool_name: {"scope", "description", "read_only", "input_schema", "facade_method"}}``
ASTRAL_TOOLS: dict[str, dict[str, Any]] = CONTRACT["tools"]

#: The exact, ordered set of tool names this SDK (and the live server) supports.
TOOL_NAMES: tuple[str, ...] = tuple(CONTRACT["dispatchable_tool_names"])

#: Every scope a framework credential may carry.
FRAMEWORK_CREDENTIAL_SCOPES: tuple[str, ...] = tuple(CONTRACT["framework_credential_scopes"])

MCP_PROTOCOL_VERSION: str = CONTRACT["mcp"]["protocol_version"]
MCP_AUDIENCE: str = CONTRACT["mcp"]["audience"]


def tools_for_scopes(scopes) -> dict[str, dict[str, Any]]:
    """The subset of ``ASTRAL_TOOLS`` a credential carrying ``scopes`` may call.

    Mirrors the server's own per-tool scope gate
    (``orchestrator.mcp_projection._framework_tools``) — never assume a scope
    unlocks a tool the server itself does not gate on it.
    """
    granted = set(scopes)
    return {name: spec for name, spec in ASTRAL_TOOLS.items() if spec["scope"] in granted}


def function_schema(name: str) -> dict[str, Any]:
    """One tool as a generic ``{name, description, parameters}`` function schema.

    This is the framework-agnostic shape every integration adapter in
    ``astral_sdk.integrations`` starts from before wrapping it for its own
    target (OpenAI function-calling, Anthropic tool-use, a LangChain
    ``StructuredTool``, ...).
    """
    spec = ASTRAL_TOOLS[name]
    return {"name": name, "description": spec["description"], "parameters": spec["input_schema"]}


def all_function_schemas() -> list[dict[str, Any]]:
    return [function_schema(name) for name in TOOL_NAMES]


__all__ = [
    "CONTRACT",
    "ASTRAL_TOOLS",
    "TOOL_NAMES",
    "FRAMEWORK_CREDENTIAL_SCOPES",
    "MCP_PROTOCOL_VERSION",
    "MCP_AUDIENCE",
    "tools_for_scopes",
    "function_schema",
    "all_function_schemas",
]
