"""Loads the Astral tool catalog from the checked-in work_contract.json (generated by
scripts/export_work_contract.py) and exposes tools_for_scopes()/function_schema() to
astral_sdk.client and the integrations adapters.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

_CONTRACT_PATH = Path(__file__).resolve().parent / "work_contract.json"


def _load_contract() -> dict[str, Any]:
    with _CONTRACT_PATH.open("r", encoding="utf-8") as handle:
        return json.load(handle)


CONTRACT: dict[str, Any] = _load_contract()

ASTRAL_TOOLS: dict[str, dict[str, Any]] = CONTRACT["tools"]

TOOL_NAMES: tuple[str, ...] = tuple(CONTRACT["dispatchable_tool_names"])

FRAMEWORK_CREDENTIAL_SCOPES: tuple[str, ...] = tuple(CONTRACT["framework_credential_scopes"])

MCP_PROTOCOL_VERSION: str = CONTRACT["mcp"]["protocol_version"]
MCP_AUDIENCE: str = CONTRACT["mcp"]["audience"]


def tools_for_scopes(scopes) -> dict[str, dict[str, Any]]:
    granted = set(scopes)
    return {name: spec for name, spec in ASTRAL_TOOLS.items() if spec["scope"] in granted}


def function_schema(name: str) -> dict[str, Any]:
    spec = ASTRAL_TOOLS[name]
    return {"name": name, "description": spec["description"], "parameters": spec["input_schema"]}


def all_function_schemas() -> list[dict[str, Any]]:
    return [function_schema(name) for name in TOOL_NAMES]


__all__ = [
    "CONTRACT",
    "ASTRAL_TOOLS",
    "TOOL_NAMES",
    "FRAMEWORK_CREDENTIAL_SCOPES",
    "MCP_PROTOCOL_VERSION",
    "MCP_AUDIENCE",
    "tools_for_scopes",
    "function_schema",
    "all_function_schemas",
]
