#!/usr/bin/env python3
"""Verify that tracked Astral source has one mutable repository owner.

The verifier reads repository content only through Git object inventories.  An
ignored or untracked working-tree file therefore cannot create an owner, hide a
duplicate, or satisfy a generated-copy declaration.

``compatibilityAdapters`` are semantic host adapters.  They are validated for
presence but never exempt copied bytes.  A byte-for-byte exception must be an
explicit ``generatedCopies`` entry whose owner source and destination both
match the declared SHA-256 digest.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import stat
import subprocess
import sys
import unicodedata
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import Any
from urllib.parse import urlsplit

MAP_FORMAT = "astral.component-ownership/v1"
REPORT_FORMAT = "astral.component-ownership-check/v1"
MAX_MAP_BYTES = 1024 * 1024

_REPOSITORY_ID = re.compile(r"^[a-z][a-z0-9-]*$")
_DOMAIN_ID = re.compile(r"^[a-z][a-z0-9-]*$")
_FULL_SHA256 = re.compile(r"^[0-9a-f]{64}$")
_GIT_OBJECT_ID = re.compile(r"^[0-9a-f]{40,64}$")
_REGULAR_MODES = frozenset({"100644", "100755"})
_WINDOWS_DEVICE_NAMES = {
    "aux",
    "con",
    "nul",
    "prn",
    *(f"com{number}" for number in range(1, 10)),
    *(f"lpt{number}" for number in range(1, 10)),
}
_WINDOWS_FORBIDDEN = frozenset('<>:"|?*')


class OwnershipError(RuntimeError):
    """The ownership contract or repository inventory is unsafe or invalid."""


@dataclass(frozen=True)
class TrackedBlob:
    """One blob in a repository commit tree."""

    path: str
    mode: str
    object_id: str


@dataclass(frozen=True)
class RepositorySpec:
    """One repository declared by the ownership map."""

    identifier: str
    canonical_url: str
    composition_path: str
    mutable_roots: tuple[str, ...]


@dataclass(frozen=True)
class ForbiddenCopy:
    """Path patterns forbidden in one non-owner repository."""

    repository: str
    patterns: tuple[PathPattern, ...]


@dataclass(frozen=True)
class OwnershipDomain:
    """One logical source domain and its only mutable owner."""

    identifier: str
    owner: str
    owned_patterns: tuple[PathPattern, ...]
    forbidden_copies: tuple[ForbiddenCopy, ...]


@dataclass(frozen=True)
class CompatibilityAdapter:
    """A semantic adapter, never a copied-source exception."""

    repository: str
    path: str
    is_tree: bool
    upstream_owner: str
    rule: str


@dataclass(frozen=True)
class GeneratedCopy:
    """One exact generated byte copy from an owner-managed source."""

    source_repository: str
    source_path: str
    destination_repository: str
    destination_path: str
    sha256: str


@dataclass(frozen=True)
class OwnershipMap:
    """Validated ownership-map data used by the audit."""

    repositories: Mapping[str, RepositorySpec]
    domains: tuple[OwnershipDomain, ...]
    compatibility_adapters: tuple[CompatibilityAdapter, ...]
    generated_copies: tuple[GeneratedCopy, ...]


@dataclass(frozen=True)
class RepositoryInventory:
    """An immutable Git tree inventory for one repository."""

    identifier: str
    root: Path
    commit: str
    tree: str
    blobs: Mapping[str, TrackedBlob]


@dataclass(frozen=True)
class PathPattern:
    """A safe repository-relative glob compiled with explicit ``**`` rules."""

    source: str
    expression: re.Pattern[str]

    @classmethod
    def compile(cls, source: str, *, field: str) -> PathPattern:
        normalized = _normalized_pattern(source, field=field)
        pieces: list[str] = ["^"]
        index = 0
        while index < len(normalized):
            character = normalized[index]
            if character == "*":
                if index + 1 < len(normalized) and normalized[index + 1] == "*":
                    index += 2
                    if index < len(normalized) and normalized[index] == "/":
                        pieces.append("(?:.*/)?")
                        index += 1
                    else:
                        pieces.append(".*")
                    continue
                pieces.append("[^/]*")
            else:
                pieces.append(re.escape(character))
            index += 1
        pieces.append("$")
        return cls(normalized, re.compile("".join(pieces)))

    def matches(self, path: str) -> bool:
        return self.expression.fullmatch(path) is not None


def _mapping(value: Any, *, field: str) -> Mapping[str, Any]:
    if not isinstance(value, dict):
        raise OwnershipError(f"{field} must be an object")
    return value


def _array(value: Any, *, field: str) -> list[Any]:
    if not isinstance(value, list):
        raise OwnershipError(f"{field} must be an array")
    return value


def _exact_keys(value: Mapping[str, Any], expected: set[str], *, field: str) -> None:
    actual = set(value)
    if actual != expected:
        missing = sorted(expected - actual)
        extra = sorted(actual - expected)
        raise OwnershipError(
            f"{field} keys differ: missing={missing!r}, extra={extra!r}"
        )


def _nonempty_string(value: Any, *, field: str) -> str:
    if not isinstance(value, str) or not value.strip() or value != value.strip():
        raise OwnershipError(f"{field} must be a non-empty trimmed string")
    return value


def _normalized_path(value: Any, *, field: str, allow_dot: bool = False) -> str:
    text = _nonempty_string(value, field=field)
    if allow_dot and text == ".":
        return text
    if text != unicodedata.normalize("NFC", text):
        raise OwnershipError(f"{field} must use Unicode NFC normalization")
    if text.startswith("/") or text.endswith("/") or "\\" in text:
        raise OwnershipError(f"{field} must be a normalized relative POSIX path")
    parts = text.split("/")
    if any(part in {"", ".", ".."} for part in parts):
        raise OwnershipError(f"{field} contains an unsafe path segment")
    for part in parts:
        stem = part.split(".", 1)[0].casefold()
        if part.casefold() == ".git" or stem in _WINDOWS_DEVICE_NAMES:
            raise OwnershipError(f"{field} contains a reserved path segment")
        if part.endswith((" ", ".")):
            raise OwnershipError(f"{field} contains a non-portable path segment")
        if any(
            character in _WINDOWS_FORBIDDEN
            or ord(character) < 32
            or ord(character) == 127
            for character in part
        ):
            raise OwnershipError(f"{field} contains an unsafe character")
    return "/".join(parts)


def _normalized_root(value: Any, *, field: str) -> str:
    text = _nonempty_string(value, field=field)
    if not text.endswith("/"):
        raise OwnershipError(f"{field} must end in '/' to declare a tree root")
    return _normalized_path(text[:-1], field=field)


def _normalized_pattern(value: Any, *, field: str) -> str:
    text = _nonempty_string(value, field=field)
    if text.startswith("/") or text.endswith("/") or "\\" in text:
        raise OwnershipError(f"{field} must be a relative POSIX glob")
    if any(character in text for character in "[]{}!?"):
        raise OwnershipError(f"{field} uses unsupported glob syntax")
    segments = text.split("/")
    if any(segment in {"", ".", ".."} for segment in segments):
        raise OwnershipError(f"{field} contains an unsafe path segment")
    for segment in segments:
        literal = segment.replace("*", "x")
        _normalized_path(literal, field=field)
    return text


def _canonical_url(value: Any, *, field: str) -> str:
    text = _nonempty_string(value, field=field)
    parsed = urlsplit(text)
    if (
        parsed.scheme != "https"
        or parsed.netloc != "github.com"
        or not parsed.path.startswith("/AstralDeep/")
        or not parsed.path.endswith(".git")
        or parsed.query
        or parsed.fragment
    ):
        raise OwnershipError(f"{field} must be a canonical AstralDeep HTTPS Git URL")
    return text


def _duplicates(values: Sequence[str]) -> list[str]:
    seen: set[str] = set()
    duplicates: set[str] = set()
    for value in values:
        key = value.casefold()
        if key in seen:
            duplicates.add(value)
        seen.add(key)
    return sorted(duplicates, key=str.casefold)


def _load_json(path: Path) -> Mapping[str, Any]:
    try:
        payload = path.read_bytes()
    except OSError as exc:
        raise OwnershipError(f"ownership map is unreadable: {path}: {exc}") from exc
    if not payload or len(payload) > MAX_MAP_BYTES:
        raise OwnershipError(f"ownership map size must be 1..{MAX_MAP_BYTES} bytes")

    def reject_duplicate(pairs: list[tuple[str, Any]]) -> dict[str, Any]:
        result: dict[str, Any] = {}
        for key, value in pairs:
            if key in result:
                raise OwnershipError(f"ownership map contains duplicate key {key!r}")
            result[key] = value
        return result

    def reject_constant(value: str) -> float:
        raise OwnershipError(f"ownership map contains non-finite number {value}")

    try:
        document = json.loads(
            payload.decode("utf-8"),
            object_pairs_hook=reject_duplicate,
            parse_constant=reject_constant,
        )
    except UnicodeDecodeError as exc:
        raise OwnershipError("ownership map is not UTF-8") from exc
    except json.JSONDecodeError as exc:
        raise OwnershipError(f"ownership map is invalid JSON: {exc.msg}") from exc
    return _mapping(document, field="ownership map")


def load_ownership_map(path: str | Path) -> OwnershipMap:
    """Load and strictly validate one version-one ownership map."""

    document = _load_json(Path(path))
    _exact_keys(
        document,
        {
            "format",
            "repositories",
            "ownershipDomains",
            "compatibilityAdapters",
            "generatedCopies",
            "ignoredPathPolicy",
            "duplicatePolicy",
        },
        field="ownership map",
    )
    if document["format"] != MAP_FORMAT:
        raise OwnershipError(f"ownership map format must be {MAP_FORMAT!r}")
    _nonempty_string(document["ignoredPathPolicy"], field="ignoredPathPolicy")
    _nonempty_string(document["duplicatePolicy"], field="duplicatePolicy")

    raw_repositories = _mapping(document["repositories"], field="repositories")
    if not raw_repositories:
        raise OwnershipError("repositories must not be empty")
    repositories: dict[str, RepositorySpec] = {}
    composition_paths: list[str] = []
    canonical_urls: list[str] = []
    for identifier in sorted(raw_repositories):
        if _REPOSITORY_ID.fullmatch(identifier) is None:
            raise OwnershipError(f"invalid repository identifier {identifier!r}")
        raw = _mapping(raw_repositories[identifier], field=f"repositories.{identifier}")
        _exact_keys(
            raw,
            {"canonicalUrl", "compositionPath", "role", "mutableRoots"},
            field=f"repositories.{identifier}",
        )
        canonical_url = _canonical_url(
            raw["canonicalUrl"], field=f"repositories.{identifier}.canonicalUrl"
        )
        composition_path = _normalized_path(
            raw["compositionPath"],
            field=f"repositories.{identifier}.compositionPath",
            allow_dot=True,
        )
        _nonempty_string(raw["role"], field=f"repositories.{identifier}.role")
        roots = tuple(
            _normalized_root(
                value, field=f"repositories.{identifier}.mutableRoots[{index}]"
            )
            for index, value in enumerate(
                _array(
                    raw["mutableRoots"],
                    field=f"repositories.{identifier}.mutableRoots",
                )
            )
        )
        if not roots:
            raise OwnershipError(
                f"repositories.{identifier}.mutableRoots must not be empty"
            )
        if duplicates := _duplicates(roots):
            raise OwnershipError(
                f"repositories.{identifier}.mutableRoots collide: {duplicates!r}"
            )
        repositories[identifier] = RepositorySpec(
            identifier,
            canonical_url,
            composition_path,
            tuple(sorted(roots)),
        )
        composition_paths.append(composition_path)
        canonical_urls.append(canonical_url)
    if duplicates := _duplicates(composition_paths):
        raise OwnershipError(f"repository composition paths collide: {duplicates!r}")
    if duplicates := _duplicates(canonical_urls):
        raise OwnershipError(f"repository canonical URLs collide: {duplicates!r}")
    roots = [spec for spec in repositories.values() if spec.composition_path == "."]
    if len(roots) != 1:
        raise OwnershipError("exactly one repository compositionPath must be '.'")

    domains: list[OwnershipDomain] = []
    domain_ids: list[str] = []
    for domain_index, item in enumerate(
        _array(document["ownershipDomains"], field="ownershipDomains")
    ):
        field = f"ownershipDomains[{domain_index}]"
        raw = _mapping(item, field=field)
        _exact_keys(raw, {"id", "owner", "ownedPaths", "forbiddenCopies"}, field=field)
        identifier = _nonempty_string(raw["id"], field=f"{field}.id")
        if _DOMAIN_ID.fullmatch(identifier) is None:
            raise OwnershipError(f"{field}.id is not normalized")
        owner = _nonempty_string(raw["owner"], field=f"{field}.owner")
        if owner not in repositories:
            raise OwnershipError(f"{field}.owner names missing repository {owner!r}")
        owned_patterns = tuple(
            PathPattern.compile(value, field=f"{field}.ownedPaths[{index}]")
            for index, value in enumerate(
                _array(raw["ownedPaths"], field=f"{field}.ownedPaths")
            )
        )
        if not owned_patterns:
            raise OwnershipError(f"{field}.ownedPaths must not be empty")
        if duplicates := _duplicates([pattern.source for pattern in owned_patterns]):
            raise OwnershipError(f"{field}.ownedPaths collide: {duplicates!r}")

        forbidden: list[ForbiddenCopy] = []
        forbidden_repositories: list[str] = []
        for copy_index, copy_item in enumerate(
            _array(raw["forbiddenCopies"], field=f"{field}.forbiddenCopies")
        ):
            copy_field = f"{field}.forbiddenCopies[{copy_index}]"
            copy_raw = _mapping(copy_item, field=copy_field)
            _exact_keys(copy_raw, {"repository", "paths"}, field=copy_field)
            repository = _nonempty_string(
                copy_raw["repository"], field=f"{copy_field}.repository"
            )
            if repository not in repositories:
                raise OwnershipError(
                    f"{copy_field}.repository names missing repository {repository!r}"
                )
            if repository == owner:
                raise OwnershipError(f"{copy_field} cannot forbid paths in its owner")
            patterns = tuple(
                PathPattern.compile(value, field=f"{copy_field}.paths[{index}]")
                for index, value in enumerate(
                    _array(copy_raw["paths"], field=f"{copy_field}.paths")
                )
            )
            if not patterns:
                raise OwnershipError(f"{copy_field}.paths must not be empty")
            if duplicates := _duplicates([pattern.source for pattern in patterns]):
                raise OwnershipError(f"{copy_field}.paths collide: {duplicates!r}")
            forbidden.append(ForbiddenCopy(repository, patterns))
            forbidden_repositories.append(repository)
        if duplicates := _duplicates(forbidden_repositories):
            raise OwnershipError(
                f"{field}.forbiddenCopies repeats repositories: {duplicates!r}"
            )
        domains.append(
            OwnershipDomain(identifier, owner, owned_patterns, tuple(forbidden))
        )
        domain_ids.append(identifier)
    if not domains:
        raise OwnershipError("ownershipDomains must not be empty")
    if duplicates := _duplicates(domain_ids):
        raise OwnershipError(f"ownership domain IDs collide: {duplicates!r}")

    adapters: list[CompatibilityAdapter] = []
    adapter_destinations: list[str] = []
    for index, item in enumerate(
        _array(document["compatibilityAdapters"], field="compatibilityAdapters")
    ):
        field = f"compatibilityAdapters[{index}]"
        raw = _mapping(item, field=field)
        _exact_keys(raw, {"repository", "path", "upstreamOwner", "rule"}, field=field)
        repository = _nonempty_string(raw["repository"], field=f"{field}.repository")
        upstream = _nonempty_string(
            raw["upstreamOwner"], field=f"{field}.upstreamOwner"
        )
        if repository not in repositories or upstream not in repositories:
            raise OwnershipError(f"{field} references a missing repository")
        if repository == upstream:
            raise OwnershipError(f"{field} upstreamOwner must differ from repository")
        raw_path = _nonempty_string(raw["path"], field=f"{field}.path")
        is_tree = raw_path.endswith("/")
        path_value = _normalized_path(
            raw_path[:-1] if is_tree else raw_path, field=f"{field}.path"
        )
        adapter = CompatibilityAdapter(
            repository,
            path_value,
            is_tree,
            upstream,
            _nonempty_string(raw["rule"], field=f"{field}.rule"),
        )
        adapters.append(adapter)
        adapter_destinations.append(f"{repository}:{path_value}")
    if duplicates := _duplicates(adapter_destinations):
        raise OwnershipError(f"compatibility adapter paths collide: {duplicates!r}")

    generated: list[GeneratedCopy] = []
    generated_destinations: list[str] = []
    for index, item in enumerate(
        _array(document["generatedCopies"], field="generatedCopies")
    ):
        field = f"generatedCopies[{index}]"
        raw = _mapping(item, field=field)
        _exact_keys(
            raw,
            {
                "sourceRepository",
                "sourcePath",
                "destinationRepository",
                "destinationPath",
                "sha256",
            },
            field=field,
        )
        source_repository = _nonempty_string(
            raw["sourceRepository"], field=f"{field}.sourceRepository"
        )
        destination_repository = _nonempty_string(
            raw["destinationRepository"], field=f"{field}.destinationRepository"
        )
        if (
            source_repository not in repositories
            or destination_repository not in repositories
        ):
            raise OwnershipError(f"{field} references a missing repository")
        if source_repository == destination_repository:
            raise OwnershipError(f"{field} source and destination must differ")
        digest = _nonempty_string(raw["sha256"], field=f"{field}.sha256")
        if _FULL_SHA256.fullmatch(digest) is None:
            raise OwnershipError(f"{field}.sha256 must be lowercase 64-hex")
        copy = GeneratedCopy(
            source_repository,
            _normalized_path(raw["sourcePath"], field=f"{field}.sourcePath"),
            destination_repository,
            _normalized_path(raw["destinationPath"], field=f"{field}.destinationPath"),
            digest,
        )
        generated.append(copy)
        generated_destinations.append(
            f"{destination_repository}:{copy.destination_path}"
        )
    if duplicates := _duplicates(generated_destinations):
        raise OwnershipError(f"generated-copy destinations collide: {duplicates!r}")

    return OwnershipMap(
        repositories,
        tuple(sorted(domains, key=lambda value: value.identifier)),
        tuple(sorted(adapters, key=lambda value: (value.repository, value.path))),
        tuple(
            sorted(
                generated,
                key=lambda value: (
                    value.destination_repository,
                    value.destination_path,
                ),
            )
        ),
    )


def _git(root: Path, arguments: Sequence[str]) -> bytes:
    environment = os.environ.copy()
    environment["GIT_NO_REPLACE_OBJECTS"] = "1"
    try:
        completed = subprocess.run(
            ["git", "-C", os.fspath(root), *arguments],
            check=False,
            capture_output=True,
            env=environment,
        )
    except OSError as exc:
        raise OwnershipError(f"could not execute git: {exc}") from exc
    if completed.returncode != 0:
        detail = completed.stderr.decode("utf-8", "replace").strip()
        raise OwnershipError(
            f"git {' '.join(arguments)} failed for repository: "
            f"{detail or 'no error output'}"
        )
    return completed.stdout


def _is_reparse_point(path: Path) -> bool:
    try:
        metadata = path.lstat()
    except OSError as exc:
        raise OwnershipError(
            f"repository root cannot be inspected: {path}: {exc}"
        ) from exc
    attributes = getattr(metadata, "st_file_attributes", 0)
    reparse_flag = getattr(stat, "FILE_ATTRIBUTE_REPARSE_POINT", 0)
    return path.is_symlink() or bool(attributes & reparse_flag)


def exact_git_root(value: str | Path) -> Path:
    """Resolve a caller-supplied path and require it to be the exact Git root."""

    candidate = Path(value).expanduser()
    if _is_reparse_point(candidate):
        raise OwnershipError(f"repository root is a reparse point: {candidate}")
    try:
        resolved = candidate.resolve(strict=True)
    except OSError as exc:
        raise OwnershipError(
            f"repository root does not resolve: {candidate}: {exc}"
        ) from exc
    if not resolved.is_dir():
        raise OwnershipError(f"repository root is not a directory: {resolved}")
    raw_root = _git(resolved, ("rev-parse", "--show-toplevel"))
    try:
        git_root = Path(os.fsdecode(raw_root).rstrip("\r\n")).resolve(strict=True)
    except OSError as exc:
        raise OwnershipError(f"Git root does not resolve: {exc}") from exc
    if git_root != resolved:
        raise OwnershipError(
            f"exact-root mismatch: requested '{resolved}', Git root is '{git_root}'"
        )
    return resolved


def inventory_repository(
    identifier: str, root: str | Path, revision: str = "HEAD"
) -> RepositoryInventory:
    """Inventory only blobs tracked by one immutable Git commit tree."""

    exact_root = exact_git_root(root)
    commit = (
        _git(exact_root, ("rev-parse", "--verify", f"{revision}^{{commit}}"))
        .decode("ascii", "strict")
        .strip()
    )
    if _GIT_OBJECT_ID.fullmatch(commit) is None:
        raise OwnershipError(f"repository {identifier} resolved an invalid commit ID")
    tree = (
        _git(exact_root, ("rev-parse", "--verify", f"{commit}^{{tree}}"))
        .decode("ascii", "strict")
        .strip()
    )
    if _GIT_OBJECT_ID.fullmatch(tree) is None:
        raise OwnershipError(f"repository {identifier} resolved an invalid tree ID")
    raw = _git(exact_root, ("ls-tree", "-r", "-z", "--full-tree", commit))
    blobs: dict[str, TrackedBlob] = {}
    for record in raw.split(b"\0"):
        if not record:
            continue
        try:
            metadata, path_bytes = record.split(b"\t", 1)
            mode_bytes, kind, object_bytes = metadata.split(b" ", 2)
            mode = mode_bytes.decode("ascii", "strict")
            object_id = object_bytes.decode("ascii", "strict")
            path = path_bytes.decode("utf-8", "strict")
        except (ValueError, UnicodeDecodeError) as exc:
            raise OwnershipError(
                f"repository {identifier} emitted an invalid Git tree record"
            ) from exc
        if kind != b"blob":
            continue
        normalized = _normalized_path(path, field=f"{identifier} tracked path")
        if normalized != path:
            raise OwnershipError(
                f"repository {identifier} has noncanonical tracked path {path!r}"
            )
        if path in blobs:
            raise OwnershipError(
                f"repository {identifier} repeats tracked path {path!r}"
            )
        if _GIT_OBJECT_ID.fullmatch(object_id) is None:
            raise OwnershipError(
                f"repository {identifier} has invalid object ID for {path!r}"
            )
        blobs[path] = TrackedBlob(path, mode, object_id)
    return RepositoryInventory(identifier, exact_root, commit, tree, blobs)


def _under_root(path: str, root: str) -> bool:
    return path == root or path.startswith(root + "/")


def _mutable(spec: RepositorySpec, path: str) -> bool:
    return any(_under_root(path, root) for root in spec.mutable_roots)


def _owned_domains(ownership: OwnershipMap, path: str) -> tuple[OwnershipDomain, ...]:
    return tuple(
        domain
        for domain in ownership.domains
        if any(pattern.matches(path) for pattern in domain.owned_patterns)
    )


def _forbidden_domains(
    ownership: OwnershipMap, repository: str, path: str
) -> tuple[OwnershipDomain, ...]:
    matches: list[OwnershipDomain] = []
    for domain in ownership.domains:
        for rule in domain.forbidden_copies:
            if rule.repository == repository and any(
                pattern.matches(path) for pattern in rule.patterns
            ):
                matches.append(domain)
                break
    return tuple(matches)


def _blob_sha256(inventory: RepositoryInventory, blob: TrackedBlob) -> str:
    content = _git(inventory.root, ("cat-file", "blob", blob.object_id))
    return hashlib.sha256(content).hexdigest()


def _violation(
    code: str,
    *,
    repository: str,
    path: str,
    domain: str | None = None,
    detail: str,
) -> dict[str, str]:
    result = {
        "code": code,
        "repository": repository,
        "path": path,
        "detail": detail,
    }
    if domain is not None:
        result["domain"] = domain
    return result


def audit_component_ownership(
    ownership: OwnershipMap,
    *,
    repository_roots: Mapping[str, str | Path],
    revisions: Mapping[str, str] | None = None,
) -> dict[str, Any]:
    """Audit exact Git trees and return a deterministic machine-readable report."""

    expected = set(ownership.repositories)
    supplied = set(repository_roots)
    if supplied != expected:
        raise OwnershipError(
            "repository roots differ from ownership map: "
            f"missing={sorted(expected - supplied)!r}, "
            f"extra={sorted(supplied - expected)!r}"
        )
    revisions = revisions or {}
    unknown_revisions = set(revisions) - expected
    if unknown_revisions:
        raise OwnershipError(
            f"revisions name unknown repositories: {sorted(unknown_revisions)!r}"
        )
    inventories = {
        identifier: inventory_repository(
            identifier,
            repository_roots[identifier],
            revisions.get(identifier, "HEAD"),
        )
        for identifier in sorted(expected)
    }

    violations: list[dict[str, str]] = []
    valid_generated: set[tuple[str, str]] = set()
    valid_generated_pairs: set[frozenset[tuple[str, str]]] = set()

    for domain in ownership.domains:
        owner_inventory = inventories[domain.owner]
        if not any(
            pattern.matches(blob.path)
            for blob in owner_inventory.blobs.values()
            for pattern in domain.owned_patterns
        ):
            violations.append(
                _violation(
                    "missing_owner",
                    repository=domain.owner,
                    path=domain.owned_patterns[0].source,
                    domain=domain.identifier,
                    detail="owner repository has no tracked path in this domain",
                )
            )

    for copy in ownership.generated_copies:
        key = (copy.destination_repository, copy.destination_path)
        source_inventory = inventories[copy.source_repository]
        destination_inventory = inventories[copy.destination_repository]
        source = source_inventory.blobs.get(copy.source_path)
        destination = destination_inventory.blobs.get(copy.destination_path)
        source_domains = _owned_domains(ownership, copy.source_path)
        if source is None:
            violations.append(
                _violation(
                    "generated_source_missing",
                    repository=copy.source_repository,
                    path=copy.source_path,
                    detail="declared generated-copy source is not tracked",
                )
            )
            continue
        if (
            len(source_domains) != 1
            or source_domains[0].owner != copy.source_repository
        ):
            violations.append(
                _violation(
                    "generated_source_not_owned",
                    repository=copy.source_repository,
                    path=copy.source_path,
                    detail="generated-copy source is not owned by exactly one source domain",
                )
            )
            continue
        if destination is None:
            violations.append(
                _violation(
                    "generated_destination_missing",
                    repository=copy.destination_repository,
                    path=copy.destination_path,
                    domain=source_domains[0].identifier,
                    detail="declared generated-copy destination is not tracked",
                )
            )
            continue
        if source.mode not in _REGULAR_MODES or destination.mode not in _REGULAR_MODES:
            violations.append(
                _violation(
                    "generated_copy_not_regular",
                    repository=copy.destination_repository,
                    path=copy.destination_path,
                    domain=source_domains[0].identifier,
                    detail="generated copies must be regular tracked files",
                )
            )
            continue
        source_digest = _blob_sha256(source_inventory, source)
        destination_digest = _blob_sha256(destination_inventory, destination)
        if source.mode != destination.mode:
            violations.append(
                _violation(
                    "generated_mode_mismatch",
                    repository=copy.destination_repository,
                    path=copy.destination_path,
                    domain=source_domains[0].identifier,
                    detail=f"source mode {source.mode} differs from destination {destination.mode}",
                )
            )
            continue
        if source_digest != copy.sha256:
            violations.append(
                _violation(
                    "generated_source_digest_mismatch",
                    repository=copy.source_repository,
                    path=copy.source_path,
                    domain=source_domains[0].identifier,
                    detail="owner-source SHA-256 does not match the declaration",
                )
            )
            continue
        if (
            destination_digest != copy.sha256
            or source.object_id != destination.object_id
        ):
            violations.append(
                _violation(
                    "generated_destination_digest_mismatch",
                    repository=copy.destination_repository,
                    path=copy.destination_path,
                    domain=source_domains[0].identifier,
                    detail="generated destination bytes do not match the owner source",
                )
            )
            continue
        valid_generated.add(key)
        valid_generated_pairs.add(
            frozenset(
                {
                    (copy.source_repository, copy.source_path),
                    (copy.destination_repository, copy.destination_path),
                }
            )
        )

    managed_count = 0
    for repository, inventory in sorted(inventories.items()):
        spec = ownership.repositories[repository]
        for path in sorted(inventory.blobs):
            if not _mutable(spec, path):
                continue
            domains = _owned_domains(ownership, path)
            forbidden = _forbidden_domains(ownership, repository, path)
            generated = (repository, path) in valid_generated
            if len(domains) > 1:
                violations.append(
                    _violation(
                        "ambiguous_owner",
                        repository=repository,
                        path=path,
                        detail="path matches multiple ownership domains: "
                        + ", ".join(domain.identifier for domain in domains),
                    )
                )
                continue
            if not domains:
                # A verified generated copy is immutable derivative output, not
                # another mutable implementation owner. Every other tracked
                # path beneath a declared mutable root must be classified.
                if not generated:
                    violations.append(
                        _violation(
                            "unowned_mutable_path",
                            repository=repository,
                            path=path,
                            detail="tracked mutable path matches no ownership domain",
                        )
                    )
            if len(domains) == 1:
                domain = domains[0]
                if repository == domain.owner:
                    managed_count += 1
                elif not generated:
                    violations.append(
                        _violation(
                            "wrong_repository_owner",
                            repository=repository,
                            path=path,
                            domain=domain.identifier,
                            detail=f"mutable owner is {domain.owner}",
                        )
                    )
            for domain in forbidden:
                if not generated:
                    violations.append(
                        _violation(
                            "forbidden_copy",
                            repository=repository,
                            path=path,
                            domain=domain.identifier,
                            detail=f"path is forbidden outside owner {domain.owner}",
                        )
                    )

    # Same Git blob at an exactly-one-domain owner source and any mutable path in
    # a declared non-owner repository is an unmanaged source duplicate. Path
    # globs remain useful diagnostics above, but renaming copied bytes must not
    # bypass content ownership. Multiple owner paths for one blob use the
    # lexicographically first path so evidence remains deterministic.
    for domain in ownership.domains:
        owner_inventory = inventories[domain.owner]
        owner_blobs: dict[str, str] = {}
        for blob in sorted(owner_inventory.blobs.values(), key=lambda item: item.path):
            source_domains = _owned_domains(ownership, blob.path)
            if len(source_domains) != 1 or source_domains[0] != domain:
                continue
            owner_blobs.setdefault(blob.object_id, blob.path)
        if not owner_blobs:
            continue
        for repository in sorted(inventories):
            if repository == domain.owner:
                continue
            inventory = inventories[repository]
            destination_spec = ownership.repositories[repository]
            for blob in sorted(inventory.blobs.values(), key=lambda item: item.path):
                if blob.object_id not in owner_blobs:
                    continue
                if not _mutable(destination_spec, blob.path):
                    continue
                key = (repository, blob.path)
                if key in valid_generated:
                    continue
                source_key = (domain.owner, owner_blobs[blob.object_id])
                if frozenset({source_key, key}) in valid_generated_pairs:
                    continue
                violations.append(
                    _violation(
                        "unmanaged_exact_duplicate",
                        repository=repository,
                        path=blob.path,
                        domain=domain.identifier,
                        detail=f"tracked bytes duplicate owner path {owner_blobs[blob.object_id]}",
                    )
                )

    for adapter in ownership.compatibility_adapters:
        inventory = inventories[adapter.repository]
        exists = (
            any(_under_root(path, adapter.path) for path in inventory.blobs)
            if adapter.is_tree
            else adapter.path in inventory.blobs
        )
        if not exists:
            violations.append(
                _violation(
                    "compatibility_adapter_missing",
                    repository=adapter.repository,
                    path=adapter.path,
                    detail="declared semantic adapter has no tracked path",
                )
            )

    # One path may violate both a broad owner rule and a narrower forbidden-copy
    # rule, but identical duplicate records are noise.  Sort and de-duplicate the
    # complete records for stable CLI and evidence output.
    unique = {
        json.dumps(item, ensure_ascii=False, sort_keys=True): item
        for item in violations
    }
    ordered_violations = [
        unique[key]
        for key in sorted(
            unique,
            key=lambda key: (
                unique[key]["repository"],
                unique[key]["path"],
                unique[key]["code"],
                unique[key].get("domain", ""),
                unique[key]["detail"],
            ),
        )
    ]
    return {
        "format": REPORT_FORMAT,
        "mapFormat": MAP_FORMAT,
        "ok": not ordered_violations,
        "repositories": [
            {
                "id": identifier,
                "compositionPath": ownership.repositories[identifier].composition_path,
                "commit": inventories[identifier].commit,
                "tree": inventories[identifier].tree,
                "trackedBlobCount": len(inventories[identifier].blobs),
            }
            for identifier in sorted(inventories)
        ],
        "managedPathCount": managed_count,
        "verifiedGeneratedCopyCount": len(valid_generated),
        "violations": ordered_violations,
    }


def report_bytes(report: Mapping[str, Any]) -> bytes:
    """Serialize one report canonically for evidence capture."""

    return (
        json.dumps(report, ensure_ascii=False, sort_keys=True, indent=2) + "\n"
    ).encode("utf-8")


def _parse_assignments(values: Sequence[str], *, field: str) -> dict[str, str]:
    result: dict[str, str] = {}
    for value in values:
        if "=" not in value:
            raise OwnershipError(f"{field} must use REPOSITORY=VALUE syntax")
        identifier, assigned = value.split("=", 1)
        if _REPOSITORY_ID.fullmatch(identifier) is None or not assigned:
            raise OwnershipError(f"{field} contains an invalid assignment {value!r}")
        if identifier in result:
            raise OwnershipError(f"{field} repeats repository {identifier!r}")
        result[identifier] = assigned
    return result


def _default_roots(ownership: OwnershipMap, composition_root: Path) -> dict[str, Path]:
    root = exact_git_root(composition_root)
    return {
        identifier: root
        if spec.composition_path == "."
        else root / Path(*spec.composition_path.split("/"))
        for identifier, spec in ownership.repositories.items()
    }


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--ownership-map",
        default="contracts/component-ownership.json",
        help="version-one ownership map",
    )
    parser.add_argument(
        "--composition-root",
        default=".",
        help="exact AstralDeep composition Git root",
    )
    parser.add_argument(
        "--repository-root",
        action="append",
        default=[],
        metavar="REPOSITORY=PATH",
        help="override one repository root; if used, all roots must be supplied",
    )
    parser.add_argument(
        "--revision",
        action="append",
        default=[],
        metavar="REPOSITORY=REVISION",
        help="audit an immutable revision instead of HEAD for one repository",
    )
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    parser = _parser()
    arguments = parser.parse_args(argv)
    try:
        ownership = load_ownership_map(arguments.ownership_map)
        roots = _parse_assignments(arguments.repository_root, field="repository root")
        repository_roots: Mapping[str, str | Path]
        if roots:
            repository_roots = roots
        else:
            repository_roots = _default_roots(
                ownership, Path(arguments.composition_root)
            )
        revisions = _parse_assignments(arguments.revision, field="revision")
        report = audit_component_ownership(
            ownership,
            repository_roots=repository_roots,
            revisions=revisions,
        )
    except OwnershipError as exc:
        print(json.dumps({"error": str(exc)}, sort_keys=True), file=sys.stderr)
        return 2
    sys.stdout.buffer.write(report_bytes(report))
    return 0 if report["ok"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
